remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: [East Bay Mobility Index]
description: [Ranking Census Bocks by their accessibility in Berkeley, Oakland, and Emeryville]
